name: Push index.html to live Curious home page
on:
  push:
    paths:
      - 'build/index.html'
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: laveryj/curious
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: cp <path-to-curious-home>/build/index.html .
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add index.html
          git commit -m "Update index.html from curious-home"
          git push
